sieda/Sieda/Sieda/urls.py
# -*- encoding: utf-8 -*-
"""Sieda URL Configuration
"""
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
   	url(r'^', include('main.urls', namespace='main')),
	
]

sieda/Sieda/main/urls.py
# -*- coding: utf-8 -*-
"""
URLS
"""
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from . import views
from django.conf.urls import handler404

urlpatterns = [
    #url(r'^$', views.SiedaMain, name='sieda_main'),
   

    url(r'^$', 'django.contrib.auth.views.login', {'template_name':'sieda/login.html'}, name='login'),
    url(r'^cerrar/$', 'django.contrib.auth.views.logout',{'template_name':'cerrar.html'}, name='logout'),
    url(handler404,views.error404),

    #INDEX ADMINISTRADORES#
    url(r'^Sieda-admin$', views.AdminMain, name='admin_main'),
    #NUEVOS 
    url(r'^lista/maestros/$',views.Maestros_lista, name='LMaestro'),
    url(r'^lista/secciones/$',views.Secciones_lista, name='LSecciones'),
    url(r'^lista/jefes/$',views.Jefes_lista, name='LJefes'),
    url(r'^lista/preguntas/$',views.Preguntas_lista, name='LPregutas'),

    #REPORTES
    url(r'^Reporte/reporte_menu$',views.Reporte_menu, name='RMenu'),

    url(r'^Reporte/e_maestros$',views.Reporte_esp_maestros, name='REMaestros'),
   
    url(r'^Reporte/g_maestros$',views.Reporte_general_maestros, name='RGMaestros'),
    url(r'^lista/g_maestros/$',views.Lista_general_maestros, name='LGMaestros'),
    url(r'^Reporte/g_tutores$',views.Reporte_general_tutores, name='RGTutores'),
    url(r'^lista/g_tutores/$',views.Lista_general_tutores, name='LGTutores'),
    
    url(r'^Reporte/grupos/$',views.Reporte_grupal, name='RGrupal'),
    url(r'^lista/grupos/$',views.Lista_grupal, name='LGrupal'),

    url(r'^Reporte/alumnos$',views.Reporte_alumnos, name='RAlumno'),

    #ABC'S#
    url(r'^administradores/alta$', views.AdminAlta, name='admin_alta'),
    url(r'^administradores/consultar$', views.AdminConsultar, name='admin_consultar'),
    url(r'^administradores/(?P<id>[0-9]+)/eliminar$', views.AdminEliminar, name='admin_eliminar'),
    url(r'^administradores/(?P<id>[0-9]+)/modificar$', views.AdminEditar, name='admin_editar'),

    url(r'^alumnos/alta$', views.AlumnoAlta, name='alumno_alta'),
    url(r'^alumnos/consultar$', views.AlumnoConsultar, name='alumno_consultar'),
    url(r'^alumnos/(?P<id>[0-9]+)/eliminar$', views.AlumnoEliminar, name='alumno_eliminar'),
    url(r'^alumnos/(?P<id>[0-9]+)/modificar$', views.AlumnoEditar, name='alumno_editar'),

    url(r'^carreras/alta$', views.CarreraAlta, name='carrera_alta'),
    url(r'^carreras/consultar$', views.CarreraConsultar, name='carrera_consultar'),
    url(r'^carreras/(?P<id>[0-9]+)/eliminar$', views.CarreraEliminar, name='carrera_eliminar'),
    url(r'^carreras/(?P<id>[0-9]+)/modificar$', views.CarreraEditar, name='carrera_editar'),

    url(r'^maestros/alta$', views.MaestroAlta, name='maestro_alta'),
    url(r'^maestros/consultar$', views.MaestroConsultar, name='maestro_consultar'),
    url(r'^maestros/(?P<id>[0-9]+)/eliminar$', views.MaestroEliminar, name='maestro_eliminar'),
    url(r'^maestros/(?P<id>[0-9]+)/modificar$', views.MaestroEditar, name='maestro_editar'),

    url(r'^tutores/alta$', views.TutorAlta, name='tutor_alta'),
    url(r'^tutores/consultar$', views.TutorConsultar, name='tutor_consultar'),
    url(r'^tutores/(?P<id>[0-9]+)/eliminar$', views.TutorEliminar, name='tutor_eliminar'),
    url(r'^tutores/(?P<id>[0-9]+)/modificar$', views.TutorEditar, name='tutor_editar'),
    
    url(r'^grupos/alta$', views.GrupoAlta, name='grupo_alta'),
    url(r'^grupos/consultar$', views.GrupoConsultar, name='grupo_consultar'),
    url(r'^grupos/(?P<id>[0-9]+)/eliminar$', views.GrupoEliminar, name='grupo_eliminar'),
    url(r'^grupos/(?P<id>[0-9]+)/modificar$', views.GrupoEditar, name='grupo_editar'),

    url(r'^materias/alta$', views.MateriaAlta, name='materia_alta'),
    url(r'^materias/consultar$', views.MateriaConsultar, name='materia_consultar'),
    url(r'^materias/(?P<id>[0-9]+)/eliminar$', views.MateriaEliminar, name='materia_eliminar'),
    url(r'^materias/(?P<id>[0-9]+)/modificar$', views.MateriaEditar, name='materia_editar'),
    
    url(r'^jefes_de_carreras/alta$', views.JefeCarreraAlta, name='jefe_carrera_alta'),
    url(r'^jefes_de_carreras/consultar$', views.JefeCarreraConsultar, name='jefe_carrera_consultar'),
    url(r'^jefes_de_carreras/(?P<id>[0-9]+)/eliminar$', views.JefeCarreraEliminar, name='jefe_carrera_eliminar'),
    url(r'^jefes_de_carreras/(?P<id>[0-9]+)/modificar$', views.JefeCarreraEditar, name='jefe_carrera_editar'),

    url(r'^Catalogo/alta$', views.CatalogoAlta, name='catalogo_alta'),
    url(r'^Catalogo/consultar$', views.CatalogoConsultar, name='catalogo_consultar'),
    url(r'^Catalogo/(?P<id>[0-9]+)/eliminar$', views.CatalogoEliminar, name='catalogo_eliminar'),
    url(r'^Catalogo/(?P<id>[0-9]+)/modificar$', views.CatalogoEditar, name='catalogo_editar'),

    url(r'^Periodo/alta$', views.PeriodoAlta, name='periodo_alta'),
    url(r'^Periodo/consultar$', views.PeriodoConsultar, name='periodo_consultar'),
    url(r'^Periodo/(?P<id>[0-9]+)/eliminar$', views.PeriodoEliminar, name='periodo_eliminar'),
    url(r'^Periodo/(?P<id>[0-9]+)/modificar$', views.PeriodoEditar, name='periodo_editar'),

    url(r'^Seccion/alta$', views.SeccionAlta, name='seccion_alta'),
    url(r'^Seccion/consultar$', views.SeccionConsultar, name='seccion_consultar'),
    url(r'^Seccion/(?P<id>[0-9]+)/eliminar$', views.SeccionEliminar, name='seccion_eliminar'),
    url(r'^Seccion/(?P<id>[0-9]+)/modificar$', views.SeccionEditar, name='seccion_editar'),

    url(r'^Pregunta/alta$', views.PreguntaAlta, name='pregunta_alta'),
    url(r'^Pregunta/consultar$', views.PreguntaConsultar, name='pregunta_consultar'),
    url(r'^Pregunta/(?P<id>[0-9]+)/eliminar$', views.PreguntaEliminar, name='pregunta_eliminar'),
    url(r'^Pregunta/(?P<id>[0-9]+)/modificar$', views.PreguntaEditar, name='pregunta_editar'),

    url(r'^Evaluacion/$', views.Evaluacion, name='Evaluacion'),
    url(r'^Evaluacion/Sencilla/(?P<id>[0-9]+)$', views.Evaluacion_sencilla, name='Evaluacion_sencilla'),
    url(r'^Evaluacion/consultar(?P<id>[0-9]+)$', views.CatalogoPreguntas, name='Evaluacion_consultar'),
    url(r'^Evaluacion/Guardar_evaluacionSencilla/(?P<id>[0-9]+)$', views.GuardarEvaluacionSencilla, name='Guardar_evaluacionSencilla'),
    url(r'^Evaluacion/Guardar_evaluacion/(?P<id>[0-9]+)$', views.GuardarEvaluacion, name='Guardar_evaluacion'),
    url(r'^Evaluacion/fin$', views.Fin, name='fin'),

    url(r'^Comentarios/consultar$', views.ComentarioConsultar, name='comentario_consultar'),
    url(r'^Comentarios/eliminar$', views.ComentarioEliminar, name='comentario_eliminar'),

    
]
 

sieda/Sieda/templates/administrativo/reportes/reporte_alumnos.html
{% extends 'base_admin.html' %}
{% load bootstrap3 %}

{% block title %}
    Reporte de Alumnos
{% endblock %}

{% block body %}
<h1 class="page-header hidden-print " style="margin-top: -8px;">
Reporte de alumnos 
</h1> 
<div id="dvData" class="print">
<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading">
       Alumnos tutorados evaluados: {{alu_si}} | Alumnos tutorados faltantes: {{alu_no_num}} 
       <button style="margin-top: -13px" type="button" id="btnExport" class="btn btn-warning warning_22 pull-right hidden-print"><i class="fa fa-file-excel-o" aria-hidden="true"></i></button>
       <button style="margin-top: -13px" type="button" id="print"  class="btn btn-info warning_22 pull-right hidden-print"><i class="fa fa-print" aria-hidden="true"></i></button>
        <button style="margin-top: -13px" class="btn btn-info warning_22 pull-right hidden-print" type="button" onclick="history.back()"><i class="fa fa-reply" aria-hidden="true"></i></button>
    </div>

    <div class="panel-body no-padding" style="display: block;">
    	

        <table class="table table-striped" id="tblReporte">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Carrera</th>
                    <th>Grupo</th>
                    <th>Catalogo Evaluado</th>
                </tr>
            </thead>
            <tbody>
                {% for administradores in alu_no %}
                    <tr>
	                    <td>{{ administradores.first_name }} {{ administradores.last_name }}  </td>
	                    <td>{{ administradores.Carrera.Abrev_carrera }}</td> 
	                    <td>{{ administradores.Grupo }} </td>
                        <td> 
                            {% for cata in catalogos_al %}
                                {% if cata.alumnos__first_name in administradores.first_name %} 
                                 ({{cata.Descripcion}})
                                {% endif %}
                            {% endfor %} 
                        </td>                    	                
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>
</div>
{% endblock %}

{% block Reporte %}
 <script>
    $("#btnExport").click(function(e) {
        window.open('data:application/vnd.ms-excel;base64,' + $.base64.encode($('#dvData').html()));
        //window.open('data:application/vnd.ms-excel;charset=utf-8,' + encodeURIComponent($('#dvData').html()));
        e.preventDefault();
    });


$(document).on('click',"#print",function(){
        var originalContents = $("body").html();
        var printContents = $("#tblReporte").html();
        $("body").html(printContents);
        window.print();
        $("body").html(originalContents);
        return false;
});

</script>

{% endblock %}

sieda/Sieda/templates/administrativo/reportes/reporte_esp_maestros.html
{% extends 'base_admin.html' %}
{% load bootstrap3 %}

{% block title %}
    Reporte de Alumnos
{% endblock %}

{% block head %}         
        
{% endblock %}

{% block body %}

<h1 class="page-header hidden-print" style="margin-top: -8px;">
Evaluación Docente 
</h1> 
<br/>
<div id="dvData" class="print">
<h4><strong>Docente:</strong>&nbsp;{% for mat in materias %}{{mat.Nombre}}{% endfor %}</h4>
    <br>
<div class="panel panel-ut " data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading">
           
           <strong> Periodos en que el Docente ha sido Asignado como Maestro</strong>
            <button style="margin-top: -13px" class="btn btn-info warning_22 pull-right hidden-print" type="button" onclick="history.back()"><i class="fa fa-reply" aria-hidden="true"></i></button> 
            <button style="margin-top: -13px" type="button" id="btnExport" class="btn btn-warning warning_22 pull-right hidden-print"><i class="fa fa-file-excel-o" aria-hidden="true"></i></button>
    	
            <button style="margin-top: -13px" type="button" id="print"  class="btn btn-info warning_22 pull-right hidden-print"><i class="fa fa-print" aria-hidden="true"></i></button>
            <br>

    </div>
        <div class="panel-body no-padding" style="display: block;">
        	

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Materias</th>
                        <th>Grupos</th>
                        <th>Carreras</th>
                    </tr>
                </thead>
                <tbody>
                    {% for mat in materias %}
                        {% for materia in mat.Materia.all %}
                        <tr>
                            <td>
                                {{materia.Nombre}}
                            </td> 
                            <td style="text-align: center;">
                            {% for grupo  in materia.Grupos.all %}
                                ({{grupo.Cuatrimestre}}-{{grupo.Grupo}})
                            {% endfor %}
                            </td> 
                            <td>
                                {{materia.Carrera}}
                            </td> 
                        </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
        </div>

    
    <br class="hidden-print" />

    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-heading">
           
           <strong> Cerreras en que el Docente se ha desempeñado como Profesor de Tiempo Completo</strong>        
           <br>
        </div>
        <div class="panel-body no-padding" style="display: block;">
            

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Carrera</th>
                    </tr>
                </thead>
                <tbody>
                        {% for ca in carrera_c %}
                        <tr>
                            {% if ca.num > 1 %}
                                <td>{{ca.Materia__Carrera__Nombre}}</td>
                            {% endif %} 
                            
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
    <br class="hidden-print"/>    
    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-heading">
           
            <strong> Evaluación del Proceso Enseñanza-Aprendizaje</strong>      
            <br>
        </div>
        <div class="panel-body no-padding" style="display: block;">
            

            <table class="table table-striped">
                <thead>
                   <tr>
                     <th>Materia </th>
                     <th style="text-align: center;">Total Evaluados</th>
                     <th style="color:green;">Promedio</th>
                     <th style="text-align: center;">Grupos</th>
                     <th>Carrera</th>
                  </tr>
                </thead>
                <tbody>
                {% for g in maestro_g%}
                    <tr>
                        <td>{{g.Materia_id__Nombre}}</td>
                        <td style="text-align: center;">{{g.num}}</td>
                        <td style="color:green; text-align: center;">{{g.total}}</td>
                        <td style="text-align: center;">({{g.Grupo_id__Cuatrimestre}}-{{g.Grupo_id__Grupo}})</td>
                        <td>{{g.Materia_id__Carrera__Nombre}}</td>
                    </tr>
                {% endfor%}
                </tbody>
            </table>
        </div>

    </div>
    <br class="hidden-print"/>
    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-heading">
           
            <strong> Evaluación del tutor </strong>       
            <br>
        </div>
        <div class="panel-body no-padding" style="display: block;">
            

            <table class="table table-striped">
                <thead>
                   <tr>
                     <th>Grupo</th>
                     <th>Carrera</th>
                     <th style="color:green; text-align: center;">Promedio</th>
                     <th style=" text-align: center;">Sección</th>
                  </tr>
                </thead>
                <tbody>
                {% for t in tutor%}
                    <tr>
                        <td>({{t.Tutor__Grupo__Cuatrimestre}}-{{t.Tutor__Grupo__Grupo}})</td>
                        <td>{{t.Tutor__Carrera__Nombre}}</td>
                        <td style="color:green; text-align: center;" >{{t.total}}</td>
                        <td style=" text-align: center;">{{t.Seccion__Descripcion}}</td>
                    </tr>
                {% endfor%}
                </tbody>
            </table>
        </div>

    </div>
        <br class="hidden-print"/>
    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-heading">
           
           <strong>  Evaluación del docente (Puntaje obtenido entre el numero de alumnos evaluados)</strong>       
           <br>
        </div>
        <div class="panel-body no-padding" style="display: block;">
            <table class="table table-striped">
                {% regroup maestro_e by Materia__Nombre as mate_lista %}
                {% for ma in mate_lista %}
                    <tr>
                        <th>Area</th>
                        <th>{{ma.grouper}}</th>            
                    </tr> 
                    {% for me in ma.list %}   
                    <tr>
                        <td>{{me.Seccion_id__Descripcion}}</td>
                        <td style="text-align: center;">{{me.total}}</td>
                    </tr>
                    {% endfor %}
                {% endfor %} 
            </table>
        </div>

    </div>

</div>
</div>

{% endblock %}
{% block Reporte %}
 <script>
    $("#btnExport").click(function(e) {
        window.open('data:application/vnd.ms-excel;charset=UTF-8,' + encodeURIComponent($('#dvData').html()));
        e.preventDefault();

    });
    $(document).on('click',"#print",function(){
        var originalContents = $("body").html();
        var printContents = $("#dvData").html();
        $("body").html(printContents);
        window.print();
        $("body").html(originalContents);
        return false;
});

</script>
{% endblock %}

sieda/Sieda/templates/administrativo/reportes/reporte_general_maestros.html
{% extends 'base_admin.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
    Tutores registrados
{% endblock %}


{% block body %}


<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading">
        Grafica General Maestros
    </div>
    <div class="panel-body no-padding" style="display: block;">
    <div class= "boton" id="chartdiv" style="width: 100%; height: 400px; background-color: #FFFFFF;" ></div>
</div>



{% endblock %}
{% block Reporte %}
<link href="{% static 'js/amcharts/plugins/export/export.css' %}" rel='stylesheet' type='text/css' />
<script src="{% static 'js/amcharts/amcharts.js' %}"></script>
<script src="{% static 'js/amcharts/serial.js' %}"></script>
<script src="{% static 'js/amcharts/themes/light.js' %}"></script>

<script src="{% static 'js/amcharts/plugins/export/export.js' %}"></script>
<script src="{% static 'js/amcharts/plugins/export/export.config.default.js' %}"></script>

<script type="text/javascript" src="{% static 'reportes/reporte_general_maestros.js' %}"></script>

{% endblock %}




sieda/Sieda/templates/administrativo/reportes/reporte_general_tutores.html
{% extends 'base_admin.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
    Tutores registrados
{% endblock %}


{% block body %}


<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading">
        Grafica general tutores
    </div>
    <div class="panel-body no-padding" style="display: block;">
    <div class= "boton" id="chartdiv" style="width: 100%; height: 400px; background-color: #FFFFFF;" ></div>
</div>

{% endblock %}
{% block Reporte %}
<link href="{% static 'js/amcharts/plugins/export/export.css' %}" rel='stylesheet' type='text/css' />
<script src="{% static 'js/amcharts/amcharts.js' %}"></script>
<script src="{% static 'js/amcharts/serial.js' %}"></script>
<script src="{% static 'js/amcharts/themes/light.js' %}"></script>

<script src="{% static 'js/amcharts/plugins/export/export.js' %}"></script>
<script src="{% static 'js/amcharts/plugins/export/export.config.default.js' %}"></script>

<script type="text/javascript" src="{% static 'reportes/reporte_general_tutores.js' %}"></script>

{% endblock %}




sieda/Sieda/templates/administrativo/reportes/reporte_grupal.html
{% extends 'base_admin.html' %}
{% load bootstrap3 %}
{% load staticfiles %}



{% block body %}


<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading">
        Grafica Grupal
    </div>
    <div class="panel-body no-padding" style="display: block;">
    <div class= "boton" id="chartdiv" style="width: 100%; height: 400px; background-color: #FFFFFF;" ></div>
</div>



{% endblock %}
{% block Reporte %}
<link href="{% static 'js/amcharts/plugins/export/export.css' %}" rel='stylesheet' type='text/css' />
<script src="{% static 'js/amcharts/amcharts.js' %}"></script>
<script src="{% static 'js/amcharts/serial.js' %}"></script>
<script src="{% static 'js/amcharts/themes/light.js' %}"></script>

<script src="{% static 'js/amcharts/plugins/export/export.js' %}"></script>
<script src="{% static 'js/amcharts/plugins/export/export.config.default.js' %}"></script>

<script type="text/javascript" src="{% static 'reportes/reporte_grupal_maestros.js' %}"></script>

{% endblock %}




sieda/Sieda/templates/administrativo/reportes/reportes_menu.html
{% extends 'base_admin.html' %}
{% load staticfiles %}
{% block title %}
Reportes
{% endblock %}

      


{% block body %}
 
<div class="col-sm-6 col-md-4">
    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
</div>

<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading text-center">
        <h4>Acumulado de resultados: Maestros</h4>
    </div>
    <div class="panel-body no-padding" style="display: block;">
    	<img src="{% static 'img/maestro_general.png' %}" class="img-responsive center-block" style="height:202px; width:315px;"><br>
    	<div class="caption">
        <p>Gráfica donde se muestra el promedio de los maestros, obtenido de la evaluacion realizada </p>
        <hr>
        <p><a href="{% url 'main:RGMaestros' %}" class="btn btn-warning" role="button">Generar gráfica</a></p>
      </div>
    </div>
</div>

<br>
</div>
<div class="col-sm-6 col-md-4">
    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
</div>

<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading text-center">
        <h4>Acumulado de resultados: Tutores</h4>
    </div>
    <div class="panel-body no-padding" style="display: block;">
    	<img src="{% static 'img/tutor.png' %}" class="img-responsive center-block" style="height:202px; width:315px;"><br>
    	<div class="caption">
        <p>Gráfica donde se muestra el promedio de los Tutores, obtenido de la evaluacion realizada </p>
        <hr>
        <p><a href="{% url 'main:RGTutores' %}" class="btn btn-warning" role="button">Generar gráfica</a></p>
      </div>
    </div>
</div>

<br>
</div>
<div class="col-sm-6 col-md-4">
    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
</div>

<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading text-center">
        <h4>Acumulado de resultados: Grupo</h4>
    </div>
    <div class="panel-body no-padding" style="display: block;">
    	<img src="{% static 'img/grupo.png' %}" class="img-responsive center-block" style="height:202px; width:315px;" ><br>
    	<div class="caption">
        <p>Grafica donde se muestra el promedio de los maestros por grupo, obtenido de la evaluacion realizada </p>
        <hr>
        <p>
        <form action="{% url 'main:RGrupal' %}" method="GET">
        
        <select name="grupo" id="grupo" class="btn btn-default btn-sm">
	    		<option selected="selected" disabled>Grupo:</option>
	    		{% for grupo in grupos %}
	            <option value="{{ grupo.id }}">{{ grupo.Cuatrimestre }}-{{ grupo.Grupo}}</option>
	            	{% empty %}
                            <div class="alert alert-dismissible alert-warning">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <h4>No hay Grupos registrados aun!</h4>
                            </div>
	            {% endfor %}
	    </select>
        <select name="carrera" id="carrera" class="btn btn-default btn-sm">
                <option selected="selected" disabled>Carrera:</option>
                {% for carrera in carreras %}
                <option value="{{ carrera.id }}">{{ carrera.Abrev_carrera }}</option>
                    {% empty %}
                            <div class="alert alert-dismissible alert-warning">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <h4>No hay Grupos registrados aun!</h4>
                            </div>
                {% endfor %}
        </select>
	    <input type="submit" value="Generar grafica" class="btn btn-warning">
		</form>
      </div>
    </div>
</div>

<br>
</div>
<div class="col-sm-6 col-md-4">
    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
</div>

<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading text-center">
        <h4>Reporte Docente</h4>
    </div>
    <div class="panel-body no-padding" style="display: block;"><br>
    	<img src="{% static 'img/re2.png' %}" class="img-responsive center-block" ><br>
    	<div class="caption">
        <p>Reporte detallado, se explica la calificación que se obtuvo por dimensión </p>
        <hr>
        <form action="{% url 'main:REMaestros' %}" method="post">
        {% csrf_token %} 
        <select name="maestro" id="maestro" class="btn btn-default btn-sm">
                <option selected="selected" disabled>Maestro:</option>
                {% for ma in maestros %}
                <option value="{{ ma.id }}">{{ ma.Nombre}}</option>
                {% endfor %}
        </select>
        <input type="submit" value="Enviar" class="btn btn-warning">
        </form>
      </div>
    </div>
</div>

<br>
</div>

<div class="col-sm-6 col-md-4">
    <div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
</div>

<div class="panel panel-ut" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
    <div class="panel-heading text-center">
        <h4>Reporte Alumnos</h4>
    </div>
    <div class="panel-body no-padding" style="display: block;"><br>
    	<img src="{% static 'img/re.png' %}" class="img-responsive center-block" ><br>
    	<div class="caption">
        <p>Reporte de los alumnos que han realizado la evaluación por tutor </p>
        <hr>
        <form action="{% url 'main:RAlumno' %}" method="post">
        {% csrf_token %} 
        <select name="tutor" id="tutor" class="btn btn-default btn-sm">
                <option selected="selected" disabled>Tutor:</option>
                {% for tutor in tutores %}
                <option value="{{ tutor.Maestro }}">{{ tutor.Maestro__Nombre}}</option>
                {% endfor %}
        </select>
        <input type="submit" value="Enviar" class="btn btn-warning">
        </form>
      </div>
    </div>
</div>

<br>
</div>

	

{% endblock %}